### ISSUE TITLE
Free5GMano: Cannot deploy example VNF packages 

### ISSUE THREAD

**Issue by ananay** [free5gmano/kube5gnfvo#40]
Hello,

I’m having trouble deploying VNF packages with Free5GMano’s kube5gnfvo.

There is no way to delete a VNF package that I found. Atleast not in the documentation. I tried making a DELETE request but that did not work.

I tried deploying free5gcv1 from the example folder but that did not work. Error I got was “certificate expired” URL: kube5gnfvo/example/free5gcv1 at master · free5gmano/kube5gnfvo · GitHub

I tried deploying free5gcv2 from the example folder but that did not work either. I got the error that’s listed here: Device "upfgtp0" cannot created
I know how to fix this error in Free5GC standalone but when it’s deployed to free5gmano I’m unsure how this is going to be fixed.

I have not tried deploying the free5gcv2-kubevirt version but I’m yet to try that.

Is there anything else I need to deploy besides kube5gnfvo and its VNF packages?
Thanks!

– Ananay

**Comment by ji3k54j062k7** [comment]
> 
> 
> Hello,
> 
> I’m having trouble deploying VNF packages with Free5GMano’s kube5gnfvo.
> 
> There is no way to delete a VNF package that I found. Atleast not in the documentation. I tried making a DELETE request but that did not work.
> 
> I tried deploying free5gcv1 from the example folder but that did not work. Error I got was “certificate expired” URL: kube5gnfvo/example/free5gcv1 at master · free5gmano/kube5gnfvo · GitHub
> 
> I tried deploying free5gcv2 from the example folder but that did not work either. I got the error that’s listed here: Device "upfgtp0" cannot created
> I know how to fix this error in Free5GC standalone but when it’s deployed to free5gmano I’m unsure how this is going to be fixed.
> 
> I have not tried deploying the free5gcv2-kubevirt version but I’m yet to try that.
> 
> Is there anything else I need to deploy besides kube5gnfvo and its VNF packages?
> Thanks!
> 
> – Ananay
certificate expired error:
You can try to update the content of your kube5gnfvo-sa.yaml and deploy again 
Device "upfgtp0" cannot created error :
You can go to https://forum.free5gc.org/t/device-upfgtp0-cannot-created/75
This is the part about free5gc
