### ISSUE TITLE
kubectl apply -f multus-daemonset.yml

### ISSUE THREAD

**Issue by noormohammedli** [free5gmano/kube5gnfvo#44]
Hello SIr, 
I am tring to install free5GMONO and i am in the kube5gnfvo folder but when i run the example i get this error. 
Could you please help me with that? 

<img width="1167" alt="Screenshot 2021-05-21 at 12 33 52 am" src="https://user-images.githubusercontent.com/34620715/119061503-6e4dee00-b9cc-11eb-9d54-5ca98d513bc9.png">

Thanks

**Comment by ji3k54j062k7** [comment]
> 
> 
> Hello SIr,
> I am tring to install free5GMONO and i am in the kube5gnfvo folder but when i run the example i get this error.
> Could you please help me with that?
> 
> <img alt="Screenshot 2021-05-21 at 12 33 52 am" width="1167" src="https://user-images.githubusercontent.com/34620715/119061503-6e4dee00-b9cc-11eb-9d54-5ca98d513bc9.png">
> 
> Thanks

Can you show your version of kubectl? 
If the same error message appears in the `kubectl version` ,I suggest you go to https://github.com/kubernetes/kubernetes/issues/71647
